// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: schema.proto

package proto

import (
	proto "github.com/exoscale/sos/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefCountedBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blob     *proto.Blob `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	Refcount int32       `protobuf:"varint,2,opt,name=refcount,proto3" json:"refcount,omitempty"`
}

func (x *RefCountedBlob) Reset() {
	*x = RefCountedBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefCountedBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefCountedBlob) ProtoMessage() {}

func (x *RefCountedBlob) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefCountedBlob.ProtoReflect.Descriptor instead.
func (*RefCountedBlob) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *RefCountedBlob) GetBlob() *proto.Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *RefCountedBlob) GetRefcount() int32 {
	if x != nil {
		return x.Refcount
	}
	return 0
}

type BlobView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RcBlob       *RefCountedBlob `protobuf:"bytes,1,opt,name=rcBlob,proto3" json:"rcBlob,omitempty"`
	BlobOffset   int64           `protobuf:"varint,2,opt,name=blobOffset,proto3" json:"blobOffset,omitempty"` // Offset into the referenced Blob
	BlobSize     int64           `protobuf:"varint,3,opt,name=blobSize,proto3" json:"blobSize,omitempty"`     // Size to consider from the offset
	ExtentOffset int64           `protobuf:"varint,4,opt,name=extentOffset,proto3" json:"extentOffset,omitempty"`
}

func (x *BlobView) Reset() {
	*x = BlobView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobView) ProtoMessage() {}

func (x *BlobView) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobView.ProtoReflect.Descriptor instead.
func (*BlobView) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *BlobView) GetRcBlob() *RefCountedBlob {
	if x != nil {
		return x.RcBlob
	}
	return nil
}

func (x *BlobView) GetBlobOffset() int64 {
	if x != nil {
		return x.BlobOffset
	}
	return 0
}

func (x *BlobView) GetBlobSize() int64 {
	if x != nil {
		return x.BlobSize
	}
	return 0
}

func (x *BlobView) GetExtentOffset() int64 {
	if x != nil {
		return x.ExtentOffset
	}
	return 0
}

type Extent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid       string      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`              // volumeid/snapshotId
	DiskOffset int64       `protobuf:"varint,2,opt,name=diskOffset,proto3" json:"diskOffset,omitempty"` // 0=>0Mb, 16777216=>16Mb
	BlobViews  []*BlobView `protobuf:"bytes,3,rep,name=blobViews,proto3" json:"blobViews,omitempty"`
	IsSnapshot bool        `protobuf:"varint,4,opt,name=isSnapshot,proto3" json:"isSnapshot,omitempty"` // maybe this belongs in orchestrator
}

func (x *Extent) Reset() {
	*x = Extent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extent) ProtoMessage() {}

func (x *Extent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extent.ProtoReflect.Descriptor instead.
func (*Extent) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Extent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Extent) GetDiskOffset() int64 {
	if x != nil {
		return x.DiskOffset
	}
	return 0
}

func (x *Extent) GetBlobViews() []*BlobView {
	if x != nil {
		return x.BlobViews
	}
	return nil
}

func (x *Extent) GetIsSnapshot() bool {
	if x != nil {
		return x.IsSnapshot
	}
	return false
}

//
// The FoundationDB record layer needs to know about every
// top level message in an union.
type RecordTypeUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// RefCountedBlob _RefCountedBlob = 1; // nested
	// BlobView       _BlobView       = 2; // nested
	XExtent *Extent `protobuf:"bytes,3,opt,name=_Extent,json=Extent,proto3" json:"_Extent,omitempty"`
}

func (x *RecordTypeUnion) Reset() {
	*x = RecordTypeUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordTypeUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTypeUnion) ProtoMessage() {}

func (x *RecordTypeUnion) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTypeUnion.ProtoReflect.Descriptor instead.
func (*RecordTypeUnion) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{3}
}

func (x *RecordTypeUnion) GetXExtent() *Extent {
	if x != nil {
		return x.XExtent
	}
	return nil
}

var File_schema_proto protoreflect.FileDescriptor

var file_schema_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15,
	0x65, 0x78, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x09, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x54, 0x0a, 0x0e, 0x52, 0x65, 0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x42,
	0x6c, 0x6f, 0x62, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x2e, 0x73, 0x6f, 0x73,
	0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x66, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72,
	0x65, 0x66, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa9, 0x01, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x62,
	0x56, 0x69, 0x65, 0x77, 0x12, 0x3d, 0x0a, 0x06, 0x72, 0x63, 0x42, 0x6c, 0x6f, 0x62, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x65, 0x78, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x2e,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x66,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x06, 0x72, 0x63, 0x42,
	0x6c, 0x6f, 0x62, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x62, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x62, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x62, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x62, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x74, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x06, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x6b, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x6b, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x3d, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x62, 0x56, 0x69, 0x65, 0x77, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x78, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c,
	0x6f, 0x62, 0x56, 0x69, 0x65, 0x77, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x62, 0x56, 0x69, 0x65, 0x77,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x22, 0x49, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x07, 0x5f, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x78, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x31, 0x42, 0x07,
	0x42, 0x53, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x78, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x2f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData = file_schema_proto_rawDesc
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_proto_rawDescData)
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_schema_proto_goTypes = []interface{}{
	(*RefCountedBlob)(nil),  // 0: exoscale.blockstorage.RefCountedBlob
	(*BlobView)(nil),        // 1: exoscale.blockstorage.BlobView
	(*Extent)(nil),          // 2: exoscale.blockstorage.Extent
	(*RecordTypeUnion)(nil), // 3: exoscale.blockstorage.RecordTypeUnion
	(*proto.Blob)(nil),      // 4: exoscale.sos.Blob
}
var file_schema_proto_depIdxs = []int32{
	4, // 0: exoscale.blockstorage.RefCountedBlob.blob:type_name -> exoscale.sos.Blob
	0, // 1: exoscale.blockstorage.BlobView.rcBlob:type_name -> exoscale.blockstorage.RefCountedBlob
	1, // 2: exoscale.blockstorage.Extent.blobViews:type_name -> exoscale.blockstorage.BlobView
	2, // 3: exoscale.blockstorage.RecordTypeUnion._Extent:type_name -> exoscale.blockstorage.Extent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefCountedBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlobView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Extent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordTypeUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_rawDesc = nil
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
